# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "SECOMP UFS 2015"
  description: "Semana da Computação da Universidade Federal de Sergipe - 2015"
  date: "14 a 16 de janeiro"
  price: "Gratuito"
  address: "Universidade Federal de Sergipe"
  venue: "Universidade Federal de Sergipe"
  city: "São Cristóvão"

# Site info
site:
  url: "http://2015.secompufs.com"
  favicon: "http://braziljs.org/favicon.ico"
  googleanalytics: "UA-56303332-1"
  images:
    cover: "http://f.cl.ly/items/2X28422q1e3w0C2U1P3H/866591_24254643.jpg"
    facebook: "http://braziljs.org/img/fb-share.jpg"

subscribeText: "Inscreva-se!"
subscribeURL: "http://sigaa.ufs.br/"

# Active sections on the website
sections:
  about: true
  location: true
  speakers: false
  schedule: false
  sponsors: true
  partners: true
  contact: true

# The entire schedule
schedule:
  -
    name: "Check-in / Breakfast"
    time: "9h00"
  -
    name: "Linus Torvalds"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Linux Foundation"
    twitter: "linus"
    presentation:
      title: "Digging into a Linux Kernel"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "10h00"
  -
    name: "Bill Gates"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Microsoft"
    twitter: "billy95"
    presentation:
      title: "Introducing Windows 12"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "11h00"
  -
    name: "Lunch"
    time: "12h00"
  -
    name: "Chuck Norris"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Delta Command"
    twitter: "littlechuck"
    presentation:
      title: "How to kill a elephant with one finger"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "13h00"
  -
    name: "Steve Jobs"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Apple, Inc."
    twitter: "stevie"
    presentation:
      title: "Presenting iPad"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "14h00"
  -
    name: "Coffee-break"
    time: "15h00"
  -
    name: "Mark Zuckerberg"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Facebook"
    twitter: "zuck"
    presentation:
      title: "Revealing Facebook Secrets"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "16h00"
  -
    name: "Steve Wozniak"
    photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
    bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    company: "Apple, Inc."
    twitter: "woz"
    presentation:
      title: "Why do I prefer Android over iPhone"
      description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      time: "17h00"

# List of Sponsors
sponsors:
  -
    name: "Universidade Federal de Sergipe"
    logo: "./img/ufs-brasao.jpg"
    url: "http://www.ufs.br/"

# List of Partners
partners:
  -
    name: "Calicomp"
    logo: "./img/calicomp.jpg"
    url: "http://calicompufs.blogspot.com.br/"

# About section
aboutSection:
   title: "Sobre"
   text: "A SECOMP é a Semana de Computação da Universidade Federal de Sergipe, organizada pelo Calicomp - Centro Acadêmico Livre de Computação - e ocorrerá em janeiro de 2015."

# Contact section
contactSection:
   title: "Contato"
   text: "Qualquer dúvida pode ser tirada através dos contatos abaixo."
   email: "contatocalicomp@gmail.com"
   twitterURL: "http://twitter.com/calicompufs"
   twitterUsername: "@calicompufs"
   showForm: false
   form:
    action: "contato.php"
    name: "Qual o seu nome?"
    email: "Diga o seu email para contato"
    message: "Escreva sua mensagem"
    sendButton: "Enviar"

# Location section
locationSection:
   title: "Local"

# Partners section
partnersSection:
   title: "Apoio"

# Schedule section
scheduleSection:
   title: "Programação"
   text: "A programação abaixo pode sofrer alterações sem aviso prévio."
   time: "Horário"
   slot: "Sessão"
   description: "Descrição"

# Speakers section
speakersSection:
   title: "Palestrantes"

# Sponsors section
sponsorsSection:
   title: "Patrocinadores"
