# Jekyll
markdown: rdiscount
highlighter: "pygments"
permalink: /:title.html

# Conference info
conf:
  name: "SECOMP UFS 2015"
  description: "Semana da Computação da Universidade Federal de Sergipe - 2015"
  date: "14 a 16 de janeiro"
  price: "Gratuito"
  address: "Universidade Federal de Sergipe"
  venue: "Universidade Federal de Sergipe"
  city: "São Cristóvão"

# Site info
site:
  url: "http://2015.secompufs.com"
  favicon: "http://braziljs.org/favicon.ico"
  googleanalytics: "UA-56303332-1"
  images:
    cover: "./img/cover-circuit.jpg"
    facebook: "./img/secomp.jpg"

subscribeText: "Inscreva-se!"
subscribeURL: "http://sigaa.ufs.br/"

# Active sections on the website
sections:
  about: true
  c4p: true
  location: true
  speakers: true
  schedule: false
  sponsors: true
  partners: true
  contact: true

# The entire schedule
schedule:
  -
    name: "Check-in / Breakfast"
    time: "9h00"
  -
    name: "Profa. Dra. Beatriz Trinchão Andrade de Carvalho"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Msc. Bruno Otavio Piedade Prado"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Douglas Dyllon Jeronimo de Macedo"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Profa. Dra. Edilayne Meneses Salgueiro"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Edward David Moreno Ordonez"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Msc. Giovanny Fernando Lucero Palma"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Hendrik Teixeira Macedo"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Henrique Nou Schneider"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Profa. Msc. Kenia Kodel Cox"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Leonardo Nogueira Matos"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Marco Tulio Chella"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Michel dos Santos Soares"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Ricardo Jose Paiva de Britto Salgueiro"
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  -
    name: "Prof. Dr. Tarcisio da Rocha "
    photo: "./img/no-pic.png"
    bio: ""
    presentation:
      title: ""
      description: ""
  #-
  #  name: "Steve Wozniak"
  #  photo: "http://f.cl.ly/items/2A3p1N0C3c0n3N3R1w2B/speaker.jpg"
  #  bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #  company: "Apple, Inc."
  #  twitter: "woz"
  #  presentation:
  #    title: "Why do I prefer Android over iPhone"
  #    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
  #    time: "17h00"

# List of Sponsors
sponsors:


# List of Partners
partners:
  -
    name: "Calicomp"
    logo: "./img/calicomp.jpg"
    url: "http://calicompufs.blogspot.com.br/"
  - 
    name: "Universidade Federal de Sergipe"
    logo: "./img/ufs-brasao.jpg"
    url: "http://www.ufs.br/"
  - 
    name: "DCOMP"
    logo: "./img/dcomp.jpg"
    url: "http://computacao.ufs.br/"

# About section
aboutSection:
   title: "Sobre"
   text: "A SECOMP é a Semana de Computação da Universidade Federal de Sergipe, com o apoio do Departamento de Computação (DCOMP), será organizada pelo Centro Acadêmico Livre de Computação (CALICOMP) e ocorrerá nos dias 14, 15 e 16 de janeiro de 2015. A SECOMP tem como finalidade, a integração dos alunos e professores, mostrando uma visão abrangente das diversas áreas do conhecimento."

# Call for papers section
c4pSection:
   title: "Submissão de trabalhos"
   text: "A programação da SECOMP é construída através de trabalhos, pesquisas, artigos e minicursos da comunidade, além de palestrantes convidados. Se você deseja ter seu trabalho reconhecido, colaborar com a comunidade e compartilhar ideias, submeta o seu trabalho!"
   c4pUrl: "https://docs.google.com/forms/d/1Ronq75c5OBF_k_MOeWkzfPF8AzZnRzvQ36UDCvTR0kc/viewform"
   c4pCaption: "Submeta o seu trabalho através deste formulário e aguarde o contato do comitê de seleção."
   c4pRulesUrl: "https://docs.google.com/document/d/1W48CQmwFauz7TXFzA_cBZ37z5EKdqaRXlqWDmJVpxWI/pub"
   c4pRulesCaption: "As regras para a submissão de trabalhos são simples, mas não as deixe de conferir."

# Contact section
contactSection:
   title: "Contato"
   text: "Qualquer dúvida pode ser tirada através dos contatos abaixo."
   contacts:
   -
     title: "Email"
     link: "mailto:contatocalicomp@gmail.com"
   -
     title: "Facebook"
     link: "https://www.facebook.com/secompufs2015"  
   email: "contatocalicomp@gmail.com"
   twitterURL: "http://twitter.com/calicompufs"
   twitterUsername: "@calicompufs"
   showForm: false
   form:
    action: "contato.php"
    name: "Qual o seu nome?"
    email: "Diga o seu email para contato"
    message: "Escreva sua mensagem"
    sendButton: "Enviar"

# Location section
locationSection:
   title: "Local"

# Partners section
partnersSection:
   title: "Apoio"

# Schedule section
scheduleSection:
   title: "Programação"
   text: "A programação abaixo pode sofrer alterações sem aviso prévio."
   time: "Horário"
   slot: "Sessão"
   description: "Descrição"

# Speakers section
speakersSection:
   title: "Palestrantes"

# Sponsors section
sponsorsSection:
   title: "Patrocinadores"
